[pytest]
addopts = -n 6 -rA --ignore=tests/TEST_WIP --ignore=tests/TEST_WEBVIEW

markers = 
    visual_test: marks visual tests
    functional_test: marks functional tests
    regression_test: marks regression tests
    loyalty: mark test for loyalty domain
    member: mark test for member domain
    my_coupang: mark test for my coupang domain
    gateway: mark test for gateway domain
